FROM node:20 AS build

WORKDIR /app

COPY yarn.lock package.json ./
RUN yarn install

ARG BASE_URL~
ENV BASE_URL=$BASE_URL

COPY . .

RUN BASE_URL=$BASE_URL yarn build

FROM nginx:1.25 AS final

COPY --from=build /app/dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

EXPOSE 8000

CMD ["nginx", "-g", "daemon off;"]