FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

WORKDIR /app
COPY . ./
RUN dotnet restore Backend.Prod.sln && \
    dotnet publish Backend.Core/Backend.Core.Api -c Release -o /app/out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/out .
EXPOSE 5013

ENTRYPOINT ["dotnet", "Backend.Core.Api.dll"]