FROM node:20 AS base

 

WORKDIR /app



COPY package.json yarn.lock ./
COPY packages ./packages
COPY dependencies ./dependencies
COPY components ./components
COPY tests ./tests

COPY apps/serverside ./apps/serverside


RUN yarn install  


FROM base AS development
EXPOSE 3000
WORKDIR /app
CMD ["yarn", "turbo", "run", "dev", "--filter=@products/serverside"]

FROM base AS test
RUN apt-get update  && yarn playwright install chromium \
    && yarn playwright install-deps \
    && npx playwright install 



EXPOSE 5900
WORKDIR /app/tests/e2e

CMD [ "sh", "-c", "yarn chokidar \"src/**/*.spec.ts\" -c \"yarn run turbo test --filter=@products/tests-e2e\"" ]