FROM node:20 AS base


WORKDIR /app


COPY package.json yarn.lock ./
COPY packages ./packages
COPY dependencies ./dependencies
COPY components ./components

COPY apps/admin ./apps/admin

RUN yarn install


FROM base AS development

EXPOSE 3010
WORKDIR /app

CMD ["yarn", "turbo", "run", "dev",  "--filter=@products/admin"]