version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - BASE_URL=http://localhost:5013
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    command: [ "yarn", "start" ]
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: live-coding
    env_file: "./.env"
    volumes:
      - live_coding_postgres_data:/var/lib/postgresql/data

  api:
    env_file: "./.env"
    build:
      context: ./Backend/Backend.Core/Backend.Core.Api/ 
      dockerfile: Dockerfile.dev
    ports:
      - "5013:5013"
    
    environment:
      - DB_CONNECTION_STRING="Host=postgres;Database=live;Username=postgres;Password=postgres"

    depends_on:
      - postgres

    volumes:
      - ./Backend/Backend.Core:/app
      - /app/obj/
      - /app/bin/

  # api:
  #   env_file: "./.env"
  #   build:
  #     context: ./backend
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "5013:5013"

  #   depends_on:
  #     - postgres

  #   volumes:
  #     - ./backend:/app
  #     - /app/obj/
  #     - /app/bin/

volumes:
  live_coding_postgres_data:
