x-common-env-config: &env-config
  env_file:
    - ./.default.env
    - path: ./.override.env
      required: false


services:
  products_frontend:
    <<: *env-config       
    image: frontend_products_image_prod:latest
    ports:
      - "${FRONTEND_PRODUCTION_PORT}:8000"
    networks:
      - default_products_deployment_network
  products_api:
    <<: *env-config      
    image: api_products_image_prod:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
      - default_products_deployment_network
    ports:
      - "${API_PRODUCTION_PORT}:5013"      

  products_postgres:
    <<: *env-config      
    image: postgres_products_image_prod:latest
    networks:
      - default_products_deployment_network




networks:
  default_products_deployment_network:
    name: products_deployment_network