x-common-env-config: &env-config
  env_file:
    - ./.default.env
    - path: ./.override.env
      required: false

 
services:
  migrate:
    <<: *env-config      
    image: mcr.microsoft.com/dotnet/sdk:8.0
    user: "1000:1000"
    volumes:
      - ./Backend:/app
    working_dir: /app
    depends_on:         
      - products-postgres
      - products-api
    command: >
      sh -c "mkdir -p /tmp/dotnet && dotnet run --project Backend.Core/Backend.Core.Console --update-db"

    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - DOTNET_CLI_HOME=/tmp/dotnet     
