x-common-env-config: &env-config
  env_file:
    - ./.default.env
    - path: ./.override.env
      required: false


services:
  products_frontend:
    <<: *env-config
    image: sercudo/frontend_products_image_prod
    networks:
      - proxy_network    
      - default_products_deployment_network        
  products_frontend_next:
    <<: *env-config       
    image: sercudo/frontend_next_products_image_prod:latest

    networks:
      - default_products_deployment_network
  products_api:
    <<: *env-config      
    image: sercudo/api_products_image_prod:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    restart: unless-stopped
    networks:
      - default_products_deployment_network 


  products_postgres:
    <<: *env-config      
    image: sercudo/postgres_products_image_prod:latest
    networks:
      - default_products_deployment_network




networks:
  default_products_deployment_network:
    name: products_deployment_network
  proxy_network:
    external: true