x-common-env-config: &env-config
  env_file:
    - ./.default.env
    - path: ./.override.env
      required: false

 
services:
  products_frontend:
    image: sercudo/frontend_products_image_prod
    depends_on:
      - products_frontend_next
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx.prod
    
  products_frontend_next:
    image: sercudo/frontend_next_products_image_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile.serverside.prod
      args:
        NEXT_PUBLIC_BASE_URL: ${FRONTEND_PRODUCTION_URL}
    environment:
      - NEXT_PUBLIC_BASE_URL=${FRONTEND_PRODUCTION_URL}
      - NODE_ENV=production


  products_postgres:
    image: sercudo/postgres_products_image_prod
    <<: *env-config       
    build:
      context: ./db
      dockerfile: Dockerfile
       
  products_api:
    image: sercudo/api_products_image_prod
    <<: *env-config       
    build:
      context: ./Backend
      dockerfile: Backend.Core/Backend.Core.Api/Dockerfile.prod.api
    depends_on:
      - products_postgres

