FROM mcr.microsoft.com/dotnet/sdk:8.0 AS BUILD

RUN groupadd -g 1000 prodgroup \
    && useradd -m -u 1000 -g prodgroup produser

USER produser

WORKDIR /app

COPY --chown=produser:produser . ./

RUN dotnet restore && \
    dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app

COPY --from=build /app/out .
EXPOSE 5013
RUN ls -la
ENTRYPOINT ["sh", "-c", "while :; do sleep 1; done"]
#ENTRYPOINT [ "dotnet", "Backend.dll" ]

