FROM mcr.microsoft.com/dotnet/sdk:8.0

WORKDIR /app

COPY . ./

RUN dotnet restore

RUN dotnet tool install --global dotnet-ef

ENV PATH="$PATH:/root/.dotnet/tools"

EXPOSE 5013

CMD ["dotnet", "watch" , "run" , "--non-interactive", "--project", "live.backend.api/live.backend.api.csproj", "--urls", "http://0.0.0.0:5013"]


