FROM mcr.microsoft.com/dotnet/sdk:8.0

RUN groupadd -g 1000 oemgroup \
    && useradd -m -u 1000 -g oemgroup oem

USER oem

WORKDIR /app

COPY --chown=oem:oem . ./



#COPY . ./



RUN dotnet restore

RUN dotnet tool install --global dotnet-ef

ENV PATH="$PATH:/home/oem/.dotnet/tools"

EXPOSE 5013

CMD ["dotnet", "watch" , "run" , "--non-interactive", "--project", "live.backend.api/live.backend.api.csproj", "--urls", "http://0.0.0.0:5013"]


