name: Deploy to remove server

on:
    push:
        branches:
            - deploy

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
        
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Build containers
          run: docker compose -f docker-compose.prod.yml build
        - name: Save frontend image
          run: docker save frontend_products_container_prod:latest -o frontend_products_container_prod.tar
        - name: Save API Image
          run: docker save api_products_container_prod:latest -o api_products_container_prod.tar
        - name: Save postgres Image
          run: docker save postgres_products_container_prod:latest -o postgres_products_container_prod.tar
        
        - name: Setup SSH
          run: |
            mkdir -p ~/.ssh
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh-keyscan -p ${{ secrets.SSH_PORT }} ${{ secrets.SSH_REMOTE_IP }} >> ~/.ssh/known_hosts
        
        - name: Install rsync
          run: sudo apt-get install -y rsync
        - name: Deploy via rsync
          run: |
            rsync -avz --no-times --no-perms --no-group -e "ssh -p ${{ secrets.SSH_PORT }} -o StrictHostKeyChecking=no" frontend_live.tar api_live.tar postgres_live.tar docker-compose.deploy.yml docker-compose.migrate.yml docker-compose.console.yml  ${{secrets.SSH_USER}}@${{secrets.SSH_REMOTE_IP}}:${{secrets.SSH_REMOTE_PATH}}

        - name: Deploy container
          run: |
            ssh -o StrictHostKeyChecking=no -p ${{secrets.SSH_PORT}} ${{secrets.SSH_USER}}@${{secrets.SSH_REMOTE_IP}} << 'EOF'
            cd ${{secrets.SSH_BACKEND_REMOTE_PATH}}            
            docker compose -f docker-compose.prod.yml down -v  || true
            docker load -i frontend_products_container_prod.tar 
            docker load -i api_products_container_prod.tar
            docker load -i postgres_products_container_prod.tar
            rm -rf frontend_products_container_prod.tar api_products_container_prod.tar postgres_products_container_prod.tar
 
            docker compose -f docker-compose.deploy.yml up -d
            docker system prune -f 
        