name: Test


on:
    push:
        branches:
            - test


jobs:
    deploy:
        runs-on: ubuntu-latest
        
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
            - name: Test SSH Connection
              run: |
                mkdir -p ~/.ssh              
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                chmod 600 ~/.ssh/id_rsa              
                # # Save the private key to a temporary file
                # echo "$SSH_PRIVATE_KEY" > private_key
                # chmod 600 private_key
        
                # # Test the SSH connection
                # ssh -i private_key -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "echo 'SSH connection successful'"
        
                # # Clean up
                # rm -f private_key